### ISSUE TITLE
Collections Error

### ISSUE THREAD

**Issue by ryancheley** [adamghill/devmarks-menubar#1]
First off, I’m so sorry about opening this issue here. With Twitter being a dumpster fire recently, and your pinned tweet indicating you were taking time away from Twitter I wasn’t sure how else to contact you.

I’m an avid user of your site devmarks.io and I’ve run into a few issues:

1. I can’t access my profile. It returns a 500 error
2. I can’t add new collections, it returns a 500 error

I thought maybe these were related to me not having a paid account, so I splurged for one month of the ‘Developer’ level account. It looked like my transaction was successful, but I haven’t gotten a receipt yet (that might just be a timing thing though)

Anyway, I wanted to let you know about the 500 errors that I’m getting (even after the paid account)

Keep up the good work. 

Also, loved your appearance on DjangoChat with Will and Carlton. Great conversation! And thank you for all of your work in the Django Community 😁

**Comment by adamghill** [comment]
Hello! No worries. 😅 I'm glad you like devmarks, but I'm sorry you are getting 500s -- I didn't notice the error emails from Sentry somehow. I'm digging into the error and will hopefully fix it soon. I will let you know when it's cleared up. 👍

**Comment by adamghill** [comment]
I've deployed a few fixes for the errors you ran into -- I also reached out on Mastodon with more info. Going to close this issue, but hopefully we can keep chatting about improvements to `devmarks`. 👍
